// Auto-generated by sf-fetch.js — do not edit manually
window.__SF_DATA__ = {
  "certifications": [
    {
      "name": "Administrator",
      "year": "2022",
      "family": "Foundational",
      "hue": 200,
      "kind": "admin",
      "sub": "ADMIN",
      "color": "#00A1E0",
      "credId": "SF-298374",
      "verifyUrl": "https://trailhead.salesforce.com/credentials/verification",
      "img": "assets/badges/2025-03_Platform-Admin_500x490.png"
    },
    {
      "name": "Platform Developer I",
      "year": "2022",
      "family": "Developer",
      "hue": 220,
      "kind": "platform",
      "sub": "PD1",
      "color": "#0070D2",
      "credId": "SF-837462",
      "verifyUrl": "https://trailhead.salesforce.com/credentials/verification",
      "img": "assets/badges/2025-04_Badge_SF-Certified_Plat-Dev_500x490px.png"
    },
    {
      "name": "Platform Developer II",
      "year": "2023",
      "family": "Developer",
      "hue": 215,
      "kind": "platform",
      "sub": "PD2",
      "color": "#0070D2",
      "credId": "SF-948573",
      "verifyUrl": "https://trailhead.salesforce.com/credentials/verification",
      "img": "assets/badges/2021-03_Badge_SF-Certified_Platform-Developer-II_500x490px.png"
    },
    {
      "name": "JavaScript Developer I",
      "year": "2023",
      "family": "Developer",
      "hue": 45,
      "kind": "js",
      "sub": "JS-D1",
      "color": "#FFB400",
      "credId": "SF-102938",
      "verifyUrl": "https://trailhead.salesforce.com/credentials/verification",
      "img": "assets/badges/2025-03_JavaScript-Dev_500x490.png"
    },
    {
      "name": "Service Cloud Consultant",
      "year": "2023",
      "family": "Consultant",
      "hue": 175,
      "kind": "service",
      "sub": "SVC",
      "color": "#FF6F00",
      "credId": "SF-564738",
      "verifyUrl": "https://trailhead.salesforce.com/credentials/verification",
      "img": "assets/badges/2021-03_Badge_SF-Certified_Service-Cloud-Consultant_500x490px.png"
    },
    {
      "name": "OmniStudio Developer",
      "year": "2024",
      "family": "Industries",
      "hue": 280,
      "kind": "omnistudio",
      "sub": "OMNI",
      "color": "#7F00FF",
      "credId": "SF-746352",
      "verifyUrl": "https://trailhead.salesforce.com/credentials/verification",
      "img": "assets/badges/omnistudio-developer.png"
    },
    {
      "name": "Financial Services Cloud",
      "year": "2024",
      "family": "Industries",
      "hue": 145,
      "kind": "fsc",
      "sub": "FSC",
      "color": "#2E844A",
      "credId": "SF-293847",
      "verifyUrl": "https://trailhead.salesforce.com/credentials/verification",
      "img": "assets/badges/fsc.png"
    },
    {
      "name": "Agentforce Specialist",
      "year": "2025",
      "family": "AI",
      "hue": 305,
      "kind": "agentforce",
      "sub": "AGENT",
      "color": "#B14AED",
      "credId": "SF-847562",
      "verifyUrl": "https://trailhead.salesforce.com/credentials/verification",
      "img": "assets/badges/agentforce-specialist.png"
    },
    {
      "name": "Data Cloud Consultant",
      "year": "2025",
      "family": "Data & AI",
      "hue": 195,
      "kind": "datacloud",
      "sub": "DATA",
      "color": "#00B0FF",
      "credId": "SF-384756",
      "verifyUrl": "https://trailhead.salesforce.com/credentials/verification",
      "img": "assets/badges/data-cloud.png"
    },
    {
      "name": "AI Associate",
      "year": "2024",
      "family": "AI",
      "hue": 320,
      "kind": "ai",
      "sub": "AI",
      "color": "#FF77B0",
      "credId": "SF-928374",
      "verifyUrl": "https://trailhead.salesforce.com/credentials/verification",
      "img": "assets/badges/2026-01_Badge_SF-Certified_AI-Associate_500x490px_RETIRED.png"
    },
    {
      "name": "Lifecycle & Deployment Architect",
      "year": "2025",
      "family": "Architect",
      "hue": 330,
      "kind": "ai",
      "sub": "ARCH",
      "color": "#FF77B0",
      "credId": "SF-475869",
      "verifyUrl": "https://trailhead.salesforce.com/credentials/verification",
      "img": "assets/badges/2025-04_Badge_SF-Certified_Plat-Dev-LC-Dep-Arch_500x490px.png"
    },
    {
      "name": "Salesforce Associate",
      "year": "2022",
      "family": "Foundational",
      "hue": 205,
      "kind": "associate",
      "sub": "ASSOC",
      "color": "#00A1E0",
      "credId": "SF-192837",
      "verifyUrl": "https://trailhead.salesforce.com/credentials/verification",
      "img": "assets/badges/2025-03_Badge_SF-Certified_Platform-Foundations_500x490px.png"
    }
  ],
  "projects": [
    {
      "id": "banking-portal",
      "title": "Banking Public Portal",
      "role": "Lead Developer & Integration Architect",
      "client": "Tier-1 Global Financial Institution",
      "stack": [
        "Experience Cloud",
        "LWC",
        "OmniStudio",
        "MuleSoft",
        "FSC",
        "OAuth 2.0"
      ],
      "duration": "10 months",
      "team": "14",
      "impact": [
        {
          "metric": "99.98%",
          "label": "automated verification accuracy"
        },
        {
          "metric": "14 min",
          "label": "avg application to decision time"
        },
        {
          "metric": "60%",
          "label": "reduction in operational backlog"
        }
      ],
      "challenge": "Applicants suffered from disconnected loan application pathways, requiring manual verification across legacy databases and third-party credit bureaus.",
      "solution": "Designed a custom, high-security Experience Cloud public portal utilizing OmniStudio and custom LWCs. Integrated MuleSoft to run real-time 3rd-party background checks, building a 360-degree customer verification engine that securely aggregates applicant data."
    },
    {
      "id": "loan-origination",
      "title": "Loan Origination Systems",
      "role": "Salesforce Technical Architect",
      "client": "Enterprise Lending Group",
      "stack": [
        "Financial Services Cloud",
        "OmniStudio",
        "Apex Validation Engine",
        "DocuSign",
        "MuleSoft"
      ],
      "duration": "12 months",
      "team": "18",
      "impact": [
        {
          "metric": "78%",
          "label": "faster time-to-decision & funding"
        },
        {
          "metric": "0.05%",
          "label": "minimized default loan risk"
        },
        {
          "metric": "$4.2B+",
          "label": "total loan volume processed safely"
        }
      ],
      "challenge": "High default loan ratios and slow approvals due to fragmented validation scripts, insecure legacy handoffs, and labor-intensive manual audit steps.",
      "solution": "Built a secure, enterprise-grade Loan Origination System on FSC. Implemented deep data validations, automated risk-profiling calculations, and multi-tier approval routing using Apex trigger frameworks. This optimized loan success ratios while keeping risk to an absolute minimum."
    },
    {
      "id": "retail-store",
      "title": "Retail Store Application",
      "role": "Lead Developer & Solutions Designer",
      "client": "Global Telecommunications Provider",
      "stack": [
        "Communications Cloud",
        "Service Cloud",
        "Data Cloud",
        "OM Order Management",
        "MuleSoft"
      ],
      "duration": "8 months",
      "team": "10",
      "impact": [
        {
          "metric": "3.2 sec",
          "label": "instant carrier provisioning"
        },
        {
          "metric": "94%",
          "label": "first-contact resolution rate"
        },
        {
          "metric": "2M+",
          "label": "legacy records migrated to prod"
        }
      ],
      "challenge": "Retail associates lacked a cohesive digital 360 customer view, creating long wait times when ordering mobile lines, activating service, or updating legacy carrier contracts.",
      "solution": "Delivered a tablet-native Communications Cloud retail application. The app aggregates customer history via Data Cloud, orchestrates immediate SIM and network provisioning via Order Management, and manages updates to legacy carrier network systems in seconds."
    }
  ],
  "experience": [
    {
      "period": "Sep 2024 — Present",
      "role": "Salesforce Developer & Technical SME",
      "company": "K Square Group",
      "location": "Hyderabad, India",
      "tag": "SME",
      "bullets": [
        "Led delivery of three Salesforce implementations for financial services institutions, driving 100% user adoption, 60% revenue growth, and 90% CSAT.",
        "Architected and implemented custom workflows, flows, and enterprise integrations, ensuring secure data models, performance optimization, and platform scalability.",
        "Partnered with stakeholders to define solution designs, contribute to architecture decisions, and lead Agile/Scrum ceremonies from discovery to deployment.",
        "Guided junior developers through code reviews, best practices, and delivery standards to elevate overall team capability and solution quality."
      ]
    },
    {
      "period": "Oct 2021 — Sep 2024",
      "role": "Software Engineer (Salesforce)",
      "company": "Prodapt Solutions",
      "location": "Hyderabad, India",
      "tag": "Engineer",
      "bullets": [
        "Collaborated closely with business stakeholders and cross-functional teams to deliver tailored, scalable solution designs aligned to objectives.",
        "Contributed to 60% of development, building complex workflows, Apex triggers, Visualforce, LWC, OmniStudio components, and Sales/Service Cloud features.",
        "Authored technical documentation, championing best practices, data quality, and maintainable architecture for complex business logic.",
        "Executed integrations, glass-box testing, and prepared detailed unit test cases to deliver projects smoothly following Agile/Scrum."
      ]
    }
  ],
  "techGroups": [
    {
      "group": "Core Platform",
      "items": [
        [
          "Apex & Core Java",
          96
        ],
        [
          "LWC & Aura",
          94
        ],
        [
          "Salesforce Flows",
          95
        ],
        [
          "OmniStudio",
          90
        ],
        [
          "Visualforce & Flex",
          78
        ]
      ]
    },
    {
      "group": "Clouds & Architecture",
      "items": [
        [
          "Financial Services Cloud (FSC)",
          92
        ],
        [
          "Sales & Service Cloud",
          95
        ],
        [
          "Experience Cloud",
          88
        ],
        [
          "Communications Cloud",
          85
        ],
        [
          "Scalable Solution Design",
          90
        ]
      ]
    },
    {
      "group": "Integrations & APIs",
      "items": [
        [
          "REST / SOAP APIs",
          94
        ],
        [
          "Salesforce Integrations",
          92
        ],
        [
          "Platform Events & CDC",
          88
        ]
      ]
    },
    {
      "group": "DevOps & AI Tooling",
      "items": [
        [
          "DevOps & Copado CI/CD",
          86
        ],
        [
          "Prompt Builder & AI Assist",
          85
        ],
        [
          "Salesforce DX & GitHub",
          90
        ],
        [
          "Vibe Coding",
          95
        ]
      ]
    }
  ],
  "testimonials": [
    {
      "q": "Over the time we've worked together, Yusuf has consistently demonstrated a deep understanding of Salesforce and a remarkable ability to turn complex requirements into efficient, scalable solutions. Yusuf excels in coding, technical design, and translating business needs into practical Salesforce applications. His proactive approach to problem-solving, attention to detail, and ability to stay up-to-date with Salesforce's latest features make him an invaluable asset to any team.",
      "who": "Suresh Kaliamoorthi",
      "title": "Senior Salesforce Architect",
      "initials": "SK"
    },
    {
      "q": "Having worked closely with Yusuf at Prodapt for more than a year, I have seen firsthand the exceptional qualities that make him a valuable asset to any team. Yusuf is a highly skilled professional with a deep knowledge of OmniStudio and Communications cloud. He consistently demonstrated excellent problem-solving abilities, technical expertise, initiative and strong work ethic in our time working together. He has always been a reliable and proactive member of the team.",
      "who": "Milena Garro",
      "title": "Salesforce & Vlocity Developer",
      "initials": "MG"
    },
    {
      "q": "I had the pleasure of working with Yusuf on a crucial, highly complex project with a tight deadline. His exceptional organizational skills, quick problem-solving abilities, eagerness to embrace new technologies, and strong leadership qualities were truly impressive.",
      "who": "Nikunj Vadi",
      "title": "Salesforce Technical Lead/Architect",
      "initials": "NV"
    },
    {
      "q": "Yusuf always wears a techy cap for solutioning problems. Very innovative in suggesting solutions. A good technical expert in the making. All the very best Yusuf for all your endeavours.",
      "who": "Muthu Kumar Sundaram",
      "title": "Solution Architect",
      "initials": "MS"
    }
  ],
  "trailblazerStats": {
    "badges": 506,
    "pointsK": 294,
    "trails": 60,
    "superbadges": 14,
    "profileUrl": "https://www.salesforce.com/trailblazer/yusufkhan2546"
  },
  "articles": [
    {
      "title": "Bulkifying Salesforce Apex: A Patterns Guide for High-Volume Orgs",
      "summary": "Learn how to build high-performance Apex trigger handlers using map-based query structures, avoiding the 101 SOQL limit, and optimizing database transactions.",
      "urlName": "bulkifying-salesforce-apex",
      "articleNumber": "000001001",
      "publishedDate": "2026-05-15"
    },
    {
      "title": "OmniStudio Performance Tuning: Optimizing FlexCards & Integration Procedures",
      "summary": "A guide on cache strategies, limiting data payloads, and using Session Cache to speed up OmniStudio LWC rendering times in Industries clouds.",
      "urlName": "omnistudio-performance-tuning",
      "articleNumber": "000001002",
      "publishedDate": "2026-05-20"
    },
    {
      "title": "Implementing OAuth 2.0 Client Credentials Flow in Apex",
      "summary": "Best practices for building secure integrations using Salesforce Named Credentials, External Credentials, and custom authentication headers.",
      "urlName": "oauth-2-client-credentials-flow",
      "articleNumber": "000001003",
      "publishedDate": "2026-05-28"
    },
    {
      "title": "Agentforce Copilot: Building Custom Apex Actions for Intelligent Routing",
      "summary": "Learn how to author clean Invocable methods in Apex that Agentforce can call dynamically to trigger business automation flows.",
      "urlName": "agentforce-copilot-custom-actions",
      "articleNumber": "000001004",
      "publishedDate": "2026-06-02"
    }
  ]
};
